title: Cheng-Yu Liu (Louis)
description: Personal website for quantum research
remote_theme: pages-themes/minimal
plugins:
  - jekyll-remote-theme
show_downloads: false
# Add this new line to hide GitHub profile link
github_metadata: false
